### ISSUE TITLE
Random calendar generation

### ISSUE THREAD

**Issue by V13Axel** [fantasycalendar/Fantasy-Calendar#11]
This was a dumb idea I had just a second ago. Thought I'd immortalize it in Github.

In short, it could be fun to generate a randomized calendar (perhaps leveraging some of the stuff over at [https://www.fantasynamegenerators.com/](url)?). 

Let the user specify some constraints (max number of months, max number of weeks in a month, days in the year, etc), and then randomize within those bounds.

**Comment by Haxxer** [comment]
Added in 7f070e0
