### ISSUE TITLE
Clock: Time offset

### ISSUE THREAD

**Issue by Immanius** [fantasycalendar/Fantasy-Calendar#12]
When using a clock with an odd number of hours, it is impossible to put the 0 hour at the top center of the clock due to the requirement of needing a whole number.
![clock](https://user-images.githubusercontent.com/5829708/62754520-d1f46a80-ba35-11e9-9d65-28aa57a0bcab.png)

**Comment by V13Axel** [comment]
Implemented in 1ac832c1f29f5e5d74bcb057954ed4541f9d6cc5. Closing.
