### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by OriginLive** [fantasycalendar/Fantasy-Calendar#121]
With docker-compose up i get a runtime error once the docker is ready

Exception
Unable to locate Mix file: /css/app.css. (View: /fantasy-calendar/resources/views/templates/_page.blade.php)

On the website, i get errors when i try to register. The key for email conformation is invalid and i get errors on registration
```
responseText: "<br />↵<b>Fatal error</b>:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'migrated' doesn't have a default value in /fantasy-calendar/class/c_db.php:82↵Stack trace:↵#0 /fantasy-calendar/class/c_db.php(82): PDOStatement-&gt;execute()↵#1 /fantasy-calendar/class/c_user.php(303): database-&gt;execute()↵#2 /fantasy-calendar/ajax/ajax_user.php(50): user-&gt;signup('origin', 'my_email@gmai...', 'Password', 'Password')↵#3 {main}↵  thrown in <b>/fantasy-calendar/class/c_db.php</b> on line <b>82</b><br />↵".
```

**Comment by V13Axel** [comment]
Hi there!

Hmm, we were doing some updates earlier and it looks like we broke registration on www.fantasy-calendar.com.

Sorry about that! We'll get that fixed.

As for running it in docker, that sounds like it just hasn't finished fully starting yet to me. Try `docker-compose down` and then `docker-compose up` and see if it's still giving you trouble.

**Comment by V13Axel** [comment]
@OriginLive signup should be working on the main site again, let us know if it's still giving you trouble.
