### ISSUE TITLE
"Happens Once" Events not displaying

### ISSUE THREAD

**Issue by bentosquares** [fantasycalendar/Fantasy-Calendar#14]
One-time Events aren't displaying properly for me.
Steps to reproduce: 
- Create a new Event
- Add "Happens Once" Condition Preset 
- Event will not display, but is present in Event List
- can change "Year is Exactly" dropdown to "Year is or later than," enter same year, OR can remove Year condition entirely; in either case the Event will then display on calendar

Calendar: https://beta.fantasy-calendar.com/calendars/5f34d5c6b1cdd25e3f9fb46a6c90b4cb/
Event: "Hjolrig's Forge Completed" (currently not Displaying, set to 'Happens Once')

**Comment by Haxxer** [comment]
Fixed in latest commit
