### ISSUE TITLE
Unique Sprites for Full Moon (and ability to override the automatic sprite by event)

### ISSUE THREAD

**Issue by Valdore66** [fantasycalendar/Fantasy-Calendar#157]
It would be nice to have the ability to use separate sprites for the Lunar phase, in the instance that I am thinking of, there are times when the moon of the world I am working on shows a full moon, but with a different colour than normal. It would be nice to be able to set these, possibly as a unique value within the custom phase, but preferably by an option on an event.

Additionally, these can happen completely out of the blue, and unrelated to the current phase of the moon, so being able to override the phase of the moon from within an event settings would be awesome (to set the sprite to a full moon sprite for that day).

**Comment by Haxxer** [comment]
This will make it into the next major release :)
