### ISSUE TITLE
Enhancement: Uncounted Intercalary Days

### ISSUE THREAD

**Issue by Valdore66** [fantasycalendar/Fantasy-Calendar#158]
It would be great to be able to toggle intercalary days to not show numbers, but rather names.

Additionally, mid-month intercalary days currently interrupt the counting of the days of the month, so it would be good to be able to continue the counting of month days uninterrupted.

Eg. Currently, the days would be the following: day 17, intercalary day (18), day 19

Ideally, it would be possible to show the days as the following:
day 17, intercalary day, day 18

**Comment by Haxxer** [comment]
Added to 2.0.16 :)
