### ISSUE TITLE
Day Undefined?

### ISSUE THREAD

**Issue by HappyHappy-Trees** [fantasycalendar/Fantasy-Calendar#170]
More of a question than concern, but I haven't seen this on my calendar until today. What does the undefined status mean next to the day? Any way I could get rid of it?
![20210410_005143](https://user-images.githubusercontent.com/67238564/114258796-241e2980-9997-11eb-9a20-0026e3fac372.jpg)
[Calendar link](https://app.fantasy-calendar.com/calendars/a4e4330ec6e2dd179a42e17dab823085)

**Comment by Haxxer** [comment]
Please always include the link to your calendar in your issues :)

**Comment by HappyHappy-Trees** [comment]
Sorry about that! Not used to github so I might have missed that notice. Updated to include the link.

**Comment by Haxxer** [comment]
I can't see the issue on your calendar at the moment, what do I need to do to reproduce the issue?

**Comment by HappyHappy-Trees** [comment]
I'm not entirely sure, I opened the calendar in my web browser as usual and saw the day had undefined beside it whereas it hadn't had it before. I don't think it poses any concern, was just curious!
