### ISSUE TITLE
Printing Calendar in Landscape no longer available

### ISSUE THREAD

**Issue by Raulwicke** [fantasycalendar/Fantasy-Calendar#180]
When trying to print my Calendar, on Google Chrome the option to print in Landscape is no longer available (It was available prior to the 2.0 release) and on Firefox if you force it to landscape printing, the only thing that shows on the print preview is a blank calendar with the year. 

I'm attaching screenshots of both the Firefox and Chrome browsers when accessing the print screen.

![calendar_landscape_print](https://user-images.githubusercontent.com/22076031/116267778-53c48400-a742-11eb-806b-cc78ff3b4320.jpg)
![calendar_portrait_print](https://user-images.githubusercontent.com/22076031/116267818-5b842880-a742-11eb-8cc5-7ce4d4517ac0.jpg)
![calendar_portrait_print_chrome](https://user-images.githubusercontent.com/22076031/116267854-62ab3680-a742-11eb-88cc-662a55c346cd.jpg)

**Comment by V13Axel** [comment]
We have intentions to revisit printing soon, and this is one of the things that will be addressed.

I think we had done this on purpose at one point, but we chatted about it a month or so ago and neither of us remembers why!

Thanks for sticking it here for us though.

**Comment by worc** [comment]
landscape mode would be nice to have back. real world calendars in general are oriented wider than tall, and most fantasy calendars i've come across (or built myself) do the same.

and maybe this is a separate issue or a bug on my end, but it seems like there's no longer an option to print or save to pdf in color? that feels like another oversight since you can print moons and change their colors, but you won't see them in printed materials or saved pdfs.

**Comment by V13Axel** [comment]
Yep @worc, like i mentioned above, we're planning to revisit printing soon. We were juggling so much with the launch of 2.0 that printing was just a "Let's make sure it works well enough for now" kind of footnote when we were trying to make sure things were ready for launch.

Right now we're working on some adjustments to events (Like being able to override moons), and developing a Discord integration, so while this is on the list, I'm not sure when we'll get the time. I may get a chance tonight to at least look at it - But in the mean time feel free to submit a PR if you get a chance! 🙂

**Comment by V13Axel** [comment]
Looks like this was Bootstrap's fault, fairly easy to override. I'll be releasing this soon.
