### ISSUE TITLE
Moon Phases Not Syncing Between Eras

### ISSUE THREAD

**Issue by RaiPhoenix** [fantasycalendar/Fantasy-Calendar#189]
When I jump between the Era end of Gu Kug and Year 1 of Gu Tod, the moon phases are not properly synced. It is as if it's skipping the moon sprites the last week of Gu Kug and starting Gu Tod where it would if the year did not end early.

https://app.fantasy-calendar.com/calendars/cab09b54dbee63a933c3c89a3825186c/edit

1. Search Calendar for Night of Shadow event
2. Find one
3. Set Era date (This is so far only happening with Gu Tod)
4. Set Era to restart year count and end year early
5. Watch moon phases go wonky

**Comment by Haxxer** [comment]
This has been fixed in 2.1.0
