### ISSUE TITLE
Super wide calendars not displaying first dates in month

### ISSUE THREAD

**Issue by V13Axel** [fantasycalendar/Fantasy-Calendar#191]
Reported by: _Aecius_

**Description**
When using calendars that are exceptionally wide, the earlier dates in the month will not show up in view mode, even when set to its leftmost position.

**Calendar link**
https://app.fantasy-calendar.com/calendars/61b2956df0a18d74c715072de617de49

**Reproduction steps**
1) Create a calendar with monts that are roughly 30 days long
2) have a weak of the same length as the month length.
3) view the calendar in either view or edit mode. 
4) ??
5) Bugs!

![image](https://user-images.githubusercontent.com/2779682/119918816-259bb500-bf37-11eb-8571-03eb51a1fcfa.png)

**Comment by Haxxer** [comment]
This has been fixed in 2.1.0
