### ISSUE TITLE
Wrong Number of Days In Edit Event Dropdown

### ISSUE THREAD

**Issue by rampaging-poet** [fantasycalendar/Fantasy-Calendar#193]
When editing an event, the Specific Day dropdown has the wrong number of days.
![image](https://user-images.githubusercontent.com/1127153/123560777-379c8d80-d759-11eb-8245-7d8f33a65466.png)

Calendar, based on Greyhawk preset: https://app.fantasy-calendar.com/calendars/18533de0577c027503fd27c493af0bcc
Event: Vassica - Birth on 7th Readying, 353.

When editing this event, the Specific Day dropdown lists Day 1 through Day 7.  However, Readying has 28 days.  It might be grabbing the number of days from the first month in the year, a "festival" that's only one week long.

Editing the Month dropdown does not reload the Day dropdown.
Editing an event that takes place after the end of the list moves the event to the wrong day - this event was originally scheduled for 10th Readying, but moved back to the end of Fireseek instead when I edited it.

**Comment by Haxxer** [comment]
I can't replicate this - could you try to clear your cache to make sure you're on the latest code?

**Comment by rampaging-poet** [comment]
Cached cleared, issue persists.
I am on Firefox version 89.0.2, in case it ends up being browser-specific.

I cleared the cache and tried to edit the same event.  The dropdown still only showed the first seven days.

I also tried changing the current date to be in Year 353, logging out, and clearing the cache.  I then logged in again and was still able to reproduce the bug.  I wanted todetermine whether changing which year I was viewing between logging in and editing was required to reproduce the bug.

**Comment by Haxxer** [comment]
Okay, thank you for the extra details! One last question - are you reproducing this in the "edit" mode (when the left hand column has moons, months, etc) or in the view mode?

**Comment by rampaging-poet** [comment]
View Mode on the calendar.

View Calendar -> Click Event -> Edit

**Comment by rampaging-poet** [comment]
I've confirmed that this does not occur when the calendar is in Edit mode.

**Comment by Haxxer** [comment]
This has been fixed in the internal beta build. We'll keep this ticket open until the release of the next update.

**Comment by Haxxer** [comment]
This has been fixed in 2.1.0
