### ISSUE TITLE
Extra week days on leap days slow down the calendar.

### ISSUE THREAD

**Issue by Aecius** [fantasycalendar/Fantasy-Calendar#195]
**Description:**
When using the "add extra weekday" option on a each leap day of a calendar with a lot of leap days, creates a massive memory hog which slows down the tool to unworkable levels.

**Link to calendar:**
https://app.fantasy-calendar.com/calendars/dcc4c3457cbb03b228ec1cd1ae6fc16c

**Reproduction steps:**
1. Create a calendar lot of leap days (in this case 13 on a 13 year cycle, each entry offset by 1)
2. Add some eras to simulate a few millenia worth of data (around 5000 years is more than enough)
3. Go through each leap day - add a custom week day for the leap day you created earlier
4. by the 4th leap day input lag should start getting noticable, though your mileage may vary due to hardware. By around the 7th or 8th the tool will stop responding.

**Comment by Aecius** [comment]
Bug found on Firefox 89.0.2 (64-bits).

**Comment by Haxxer** [comment]
This has been fixed in 2.1.0
