### ISSUE TITLE
Editing a previously saved calendar name does not activate save button until after leaving the text entry box.

### ISSUE THREAD

**Issue by Immanius** [fantasycalendar/Fantasy-Calendar#196]
I know it's a super minor issue from a UX point of view, but figured I'd put it here so you all can track it.

Steps to reproduce:
open a previously saved calendar
change the calendar name and nothing else
save button is not usable until you have left the calendar name text entry box.

**Comment by Haxxer** [comment]
This has been fixed in 2.1.0
