### ISSUE TITLE
Uncaught InternalError: too much recursion after event based Event

### ISSUE THREAD

**Issue by Aecius** [fantasycalendar/Fantasy-Calendar#197]
**Description:**
While working on the month bases version of the Xuunthurian calendar I ran into a bug where creating a moon based event that checks for the existence of another moon based event on a completely different date causes an error stating:
```
 Uncaught InternalError: too much recursion
 check_event_chain https://app.fantasy-calendar.com/js/calendar/calendar_event_ui.js?id=50deea5a5c9498153187:2454
    check_event_chain https://app.fantasy-calendar.com/js/calendar/calendar_event_ui.js?id=50deea5a5c9498153187:2466
    check_event_chain https://app.fantasy-calendar.com/js/calendar/calendar_event_ui.js?id=50deea5a5c9498153187:2466
    check_event_chain https://app.fantasy-calendar.com/js/calendar/calendar_event_ui.js?id=50deea5a5c9498153187:2466
    check_event_chain https://app.fantasy-calendar.com/js/calendar/calendar_event_ui.js?id=50deea5a5c9498153187:2466
    check_event_chain https://app.fantasy-calendar.com/js/calendar/calendar_event_ui.js?id=50deea5a5c9498153187:2466
    check_event_chain https://app.fantasy-calendar.com/js/calendar/calendar_event_ui.js?id=50deea5a5c9498153187:2466
    check_event_chain https://app.fantasy-calendar.com/js/calendar/calendar_event_ui.js?id=50deea5a5c9498153187:2466
  ```

The events are there to serve as a debugging tool for the tweaking of leap days:

**Link to calendar:**
https://app.fantasy-calendar.com/calendars/b16d2337c79d460094d94a7fc0ef3029/edit

**Reproduction steps:**
1. Create a calendar like the one linked above (in this case a calendar consisting of a single 26 day month, with a 26.604 day moon)
2. create at least 3 leap days with a frequency of 10 and and offset so that the full moon should (usually) fall on the first of the month.
3. Create two events: The first event is Test which has the conditions "Moon phase is exactly Full Moon" AND "Moon-month phase count is exactly 1" AND "Day in Month is exactly 2" - This event basically serves as a quick check for whether the first of the month is indeed a full moon.
4. Create a second event with the conditions "Day in month is exactly 27" AND "Moon phase is Exactly Full Moon" - to check for full moons whenever a leap day pops up.
5. Alter the first event with the additional condition AND "Event <Second event> happens in the next 27 days." - The error should pop up at this point.

**Comment by Haxxer** [comment]
This has been fixed in 2.1.0
