### ISSUE TITLE
JSON export/import failure

### ISSUE THREAD

**Issue by Immanius** [fantasycalendar/Fantasy-Calendar#198]
exporting a working calendar from fantasy calendar, and then importing the same calendar unchanged does not always succeed.
calendar data in question is in @V13Axel s possession. 

The import fails with an error:
<Event Name> does not have valid limited repeat num data

If you need more info/link to the calendar/whatever, tag me in discord.

**Comment by Haxxer** [comment]
This has been fixed in 2.1.0
