### ISSUE TITLE
Links to specific months and days is unreliable

### ISSUE THREAD

**Issue by sashemi** [fantasycalendar/Fantasy-Calendar#199]
Hello,

I am describing 3 observations with Fantasy Calendar:

1. The right click menu which allows setting Preview Date, or Copy Link to day which is clicked on will be unavailable. This happens when switching between view/edit cycles or if flipping through years of a calendar. The menu returns on a refresh
2. When linked to any month except the first ("0") the link will not reliably take you to the right day.
See:
https://app.fantasy-calendar.com/calendars/325349d50d9915104d1f0f669c5e11db?year=256&month=0&day=1
https://app.fantasy-calendar.com/calendars/325349d50d9915104d1f0f669c5e11db?year=256&month=3&day=1
https://app.fantasy-calendar.com/calendars/325349d50d9915104d1f0f669c5e11db?year=256&month=9&day=1
https://app.fantasy-calendar.com/calendars/325349d50d9915104d1f0f669c5e11db?year=256&month=12&day=1
https://app.fantasy-calendar.com/calendars/325349d50d9915104d1f0f669c5e11db?year=256&month=14&day=1

3. When linking to any day except for "1" the link does not work - ie: it transports you to "current year and day" always.

Side note for #2: I think using "0" for first month is probably unintuitive since common use is that first month is "1" in most date notations.

**Comment by Haxxer** [comment]
This has been fixed in 2.1.0
