### ISSUE TITLE
Counting of day of season after a year ends may be inaccurate

### ISSUE THREAD

**Issue by sashemi** [fantasycalendar/Fantasy-Calendar#200]
Hello,

I am noticing that events scheduled using "Season day is" are being placed on a day after the actual day.

Calendar link: https://app.fantasy-calendar.com/calendars/325349d50d9915104d1f0f669c5e11db?year=123&month=0&day=1

**Season first days seem to work reliably**
The day 12-8-122 (previous year, Nferzhel is 12th month) is summer day #1.

The event "Start of Summer" falls on the correct day.

**Season Day is Exactly works in the same year**
The day 6-13-123 (current year per above link, Apophet is 6th month) is bleak day #1

Far Equinox event scheduled for 109th day of bleak falls on 10-4 which is exactly 109th day of the season.

***Season Day in next year after start of season falls on wrong day**
Far Equinox event scheduled for 95th day of summer falls on 1-12, which is summer day #96 and not 95.

So I conclude that season day counting with a year break in the middle is what is adding an extra day to the count (as Wasp has already debugged).

Thanks!

**Comment by Haxxer** [comment]
This has been fixed in 2.1.0
