### ISSUE TITLE
Weekday Overflow Skips some years!

### ISSUE THREAD

**Issue by Royal-Planet** [fantasycalendar/Fantasy-Calendar#201]
Some years in the future seem to ignore what the previous year's weekday was, this also seems to mess with events based on other events. I have an event that checks what type of year it should be based on a festival at the end of the previous, this seems to get the wrong answer when this skip in weekday overflow occurs.

https://app.fantasy-calendar.com/calendars/01b70bb82d21ba4b3a126156d8fcc85b

Reproduction steps
1. Have 4 weekdays
2. Have 8 Months
3. Leap year once every 2 years, that changes one month to 5 weekdays, when it occurs
4. Set week overflow on
5. Be in year 4367 - 4368

Year 4368 should start on the 4th weekday, but starts on the first, and labels the wrong type of year ( which is an event on the 1st day of the 1st month)

**Comment by Haxxer** [comment]
This is a known bug, weekday overflow with leaping weekday leap days is **not** supported, contrary to the option to turn it on. We'll be fixing this by disabling the option to turn on overflow in a future update.

There are currently no plans to support this in the future, sadly.
