### ISSUE TITLE
Some events are missing from the calendar

### ISSUE THREAD

**Issue by Joscrama** [fantasycalendar/Fantasy-Calendar#216]
**Description**

When I accessed my calendar today, I noticed how some of my events were missing (it was Winter Epinox at the time). When I started editing my calendar, I saw that this event was still among the list of events (and was not hidden). When I then created a new event (last event named "Murky Bayou"), I saw it didn't appear on the calendar (but it did appear in my list of events when editing the calendar).

**Link to calendar:**

[https://app.fantasy-calendar.com/calendars/bb9b7122dbf02d8c5a733f33398dd220](https://app.fantasy-calendar.com/calendars/bb9b7122dbf02d8c5a733f33398dd220)

**Reproduction steps:**

_Missing Winter Epinox event_
1. Opened the calendar
2. Noticed missing Winter Epinox event

_Missing new event_
1. Opened the edit calendar screen
2. Clicked on the "Create event" button on the calendar day I want to add the event day to (2nd of Uktar in this case)
3. Filled in event name and description
4. Saved event
5. Noticed missing event on calendar, but is present in list of events (on the left side of the screen)

**Comment by Haxxer** [comment]
Thank you for the report, this was just fixed in 2.1.3
