### ISSUE TITLE
Option to preserve weekday across intercalary months?

### ISSUE THREAD

**Issue by Porges** [fantasycalendar/Fantasy-Calendar#227]
Hi, I’m trying to recreate the Warhammer Fantasy Role Play calendar. Everything works great, the solstices and moon phases line up exactly as I expect, except that after an intercalary day, the start of the month is always back on the first day.

I'd like to be able to preserve the day, so that in this example, the 1st of Pflugzeit should be Aubentag.
![image](https://user-images.githubusercontent.com/12575/141932313-bde18c1b-d08b-4f7b-9bfa-35ec522430d1.png)

Thanks!

**Comment by Haxxer** [comment]
So you want to preserve the weekday flow? Is "Overflow Weekdays" enabled under the "Weekdays" menu?

**Comment by Porges** [comment]
Yes, Overflow Weekdays is enabled.

**Comment by Haxxer** [comment]
Could you link us your calendar?

**Comment by Porges** [comment]
Actually maybe the problem is that Overflow Weekdays isn't working? 

![image](https://user-images.githubusercontent.com/12575/142055366-32ceeaa3-56ae-48e8-a39e-4e4df5011f3c.png)

My calendar [is here](https://app.fantasy-calendar.com/calendars/f838cdb9656cd084ea9aa8a0e78bc76f).

**Comment by Haxxer** [comment]
That is bizarre, I'll look into it tonight

**Comment by Haxxer** [comment]
Thank you for the report, this was just fixed in 2.1.3

**Comment by Porges** [comment]
> Thank you for the report, this was just fixed in 2.1.3

Looks perfect now, thanks!
