### ISSUE TITLE
[BUG] Events: selecting condition preset doesn't populate month

### ISSUE THREAD

**Issue by Porges** [fantasycalendar/Fantasy-Calendar#229]
**Link to your calendar**
[Link to calendar](https://app.fantasy-calendar.com/calendars/f838cdb9656cd084ea9aa8a0e78bc76f)

**Describe the bug/reproduce**

When I am creating an event and choose a month preset from the drop-down, the month is not populated in the condition.
![image](https://user-images.githubusercontent.com/12575/142058253-a445f603-78bf-4840-a144-9cfb657afb05.png)

**Expected behavior**
The month should be populated in the condition.

**Desktop (please complete the following information):**
 - Browser: Edge Version 95.0.1020.53 (Official build) (64-bit)

**Comment by Haxxer** [comment]
Thank you for the report, this was just fixed in 2.1.3
