### ISSUE TITLE
[BUG] On Import Events' Event Category Set to Null

### ISSUE THREAD

**Issue by KDHaro** [fantasycalendar/Fantasy-Calendar#287]
**Link to your calendar**
https://app.fantasy-calendar.com/calendars/e4ae1abcc70aeedcc4464f7e88646b09

**Describe the bug**
When importing a calendar from JSON, any events that had an Event Category assigned lose that relationship. The events are created and the event categories are created, but the events seem to have their category field set to null after import (judging by the newly created calendar's exported JSON).

**To Reproduce**
1. Create Event Category
2. Create Event and assign Event Category
3. Save Changes
4. Export Calendar
6. Create New Calendar, Load custom JSON, Paste exported JSON
7. Examine event: No Category listed
8. Save new calendar
9. Export new calendar
10. Examine JSON, event_category_id now set to null

**Expected behavior**
Events are created and linked to their Event Category on import

**Screenshots**
The newly recreated events will look correct because they had their visualization details exported
However, they are no longer tied to the category

**Desktop (please complete the following information):**
Brave 1.18.79 (Chromium 87.0.4280.141)
Chrome 104.0.5112.81

**Additional context**

**Comment by V13Axel** [comment]
Interesting! I have a theory as to why this might be happening, I'll take a look soon.
