### ISSUE TITLE
[BUG] Javascript errors on selfhosted environment

### ISSUE THREAD

**Issue by MrShibe** [fantasycalendar/Fantasy-Calendar#290]
**Link to your calendar**
Self-hosted environment

**Describe the bug**
On a fresh install, I am able to perform most functionality (e.g. signup, begin creating a calendar) but certain functions cause javascript errors. Noticebly opening calendar presets or attempting to save a calendar.

Choose a calendar preset error:

```
Error: TypeError: data.statements is undefined in file https://calendar.mydomain.com/_debugbar/assets/javascript?v=1661717097 on line 2243
Error: TypeError: this.presets.sslice is not a function in file https://calendar.mydomain.com/js/app.js?id=4311c56ee42a8d31bcfc90dfdd101a6d on line 2
Error: TypeError: this.presets.sslice is not a function in file https://calendar.mydomain.com/js/app.js?id=4311c56ee42a8d31bcfc90dfdd101a6d on line 2
```
Save Calendar error:
```
Error: TypeError: data.statements is undefined in file https://calendar.mydomain.com/_debugbar/assets/javascript?v=1661717097 on line 2243
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data (F12 to see more detail)
```

**To Reproduce**
1. Create a calendar (on self-hosted environment)
2. Click on "Choose a calendar preset"

**Expected behavior**
Presets appear and one can be selected.

**Desktop (please complete the following information):**
 - Firefox 104.0 (64-bit)
 - Chrome 104.0.5112.102 (Official Build) (64-bit)

**Additional context**
I appreciate docker is the go to for most people, but due to the lack of documentation on selfhosted enviroment setups, I figured it best to lay out the steps I've taken, to make sure I'm not making any obvious blunders (which I don't _think_ I am, but can never be sure):

- Ensured pre-requisites were installed
- Ensured permissions were correctly set
- Configured .env (generted app key, set APP_URL and mysql details, also have tried configuring ASSET_URL and MIX_ASSET_URL to see if that made any difference)
- Configured dedicated nginx subdomain with root set to public folder (have ensured this matched the nginx configuration the docker setup uses just in case, so pretty confident in this)
- Ran setup commands (composer install, npm install, npm run development)

**Comment by V13Axel** [comment]
Interesting - it seems like there might be something missing in terms of the presets. Can you try `artisan db:seed` for me, and see if that improves anything?

**Comment by MrShibe** [comment]
I'm doing the initial database seeding with `artisan migrate:fresh --seed` which gives the following output:

```
Migration table not found.
Migration table created successfully.
Loading stored database schema: /usr/share/nginx/Fantasy-Calendar/database/schema/mysql-schema.dump
Loaded stored database schema. (251.27ms)
Migrating: 2019_12_14_000001_create_personal_access_tokens_table
Migrated:  2019_12_14_000001_create_personal_access_tokens_table (20.74ms)
Migrating: 2021_10_08_172117_add_requests_table
Migrated:  2021_10_08_172117_add_requests_table (15.02ms)
Migrating: 2021_10_17_181358_update_discord_auths_table
Migrated:  2021_10_17_181358_update_discord_auths_table (35.69ms)
Migrating: 2021_10_29_014406_rename_old_calendars_table
Migrated:  2021_10_29_014406_rename_old_calendars_table (3.88ms)
Migrating: 2021_10_29_025037_rename_calendars_beta_table_to_calendars
Migrated:  2021_10_29_025037_rename_calendars_beta_table_to_calendars (2.78ms)
Migrating: 2022_01_29_215043_increase_tracked_requests_target_column_length
Migrated:  2022_01_29_215043_increase_tracked_requests_target_column_length (4.39ms)
Seeding: Database\Seeders\PoliciesSeeder
Seeded:  Database\Seeders\PoliciesSeeder (3.94ms)
Seeding: Database\Seeders\AgreementsSeeder
Seeded:  Database\Seeders\AgreementsSeeder (0.97ms)
Seeding: Database\Seeders\UsersSeeder
Seeded:  Database\Seeders\UsersSeeder (46.29ms)
Seeding: Database\Seeders\PresetsSeeder
Seeded:  Database\Seeders\PresetsSeeder (20.56ms)
Database seeding completed successfully.
```
This does populate the presets table with the Gregorian Calendar entry.

If I try to run `artisan db:seed` then it fails because UsersSeeder tries to add a duplicate user. If I manually run the other seeder classes then that works (including the PresetsSeeder) but there doesn't seem to be a change in either the database (as to my eyes it looks to be successfully seeded already) or the error.

**Comment by V13Axel** [comment]
Interesting! Apologies for the relative radio silence, I'll be trying to reproduce this this weekend.

**Comment by V13Axel** [comment]
Hey there, finally getting around to this one.

So I just created a brand new Linux machine and installed Fantasy Calendar to it, without any of my existing credentials or settings from my usual development environment.

I simply installed `make`, `docker`, and `docker-compose`, and then ran `make` ... and was up and running within a few minutes, once all the images were downloaded and built and such.

Are you still having this issue? If so, feel free to drop by our Discord and we'll gladly help out. Otherwise, I'm not convinced there is a bug here to address.

**Comment by MrShibe** [comment]
Hi, thanks for the reply. No worries about the delay, appreciate you work on this in your free time and have other parts of the project to work on.

My issue is that I'm attempting to run the this outside of a docker environment. When attempting to run it inside a docker environment (on a test linux box) then it works without problem (as per your tests); when I attempt to run it in a self-hosted environment without docker, as a laravel app, then I encounter the errors described above, despite other laravel apps working. I've gone through the docker environment configuration and don't see any dependency/configuration mismatches, though it's possible I'm missing something.

Or are you saying that the app is only supported in a docker environment?

**Comment by V13Axel** [comment]
Nope. That's not what I'm saying at all. It's a Laravel app, should run anywhere Laravel apps run. I'm just saying this looks and smells to me like an environment issue, not an issue with Fantasy Calendar or its code... and thus is not something that belongs in a Github issue as a "bug".

To further clarify, I actually run FC outside of a Docker environment locally using Laravel Valet (cpriego's Linux fork) most of the time, and I have no such issues there, either.

Just to make sure, have you run `npm run production`, to build the latest assets? Honestly your first error is perplexing to me, as the repo doesn't contain the string `sslice` at all.

If that doesn't fix it, come jump into our Discord server (https://app.fantasy-calendar.com/discord-server) and I'll see what I can do to help in a more real-time/direct fashion.
