### ISSUE TITLE
[BUG] Fail to Clone

### ISSUE THREAD

**Issue by VishwaJay** [fantasycalendar/Fantasy-Calendar#294]
**Describe the bug**
GitHub Desktop is telling me:

> Authentication failed. Some common reasons include:
> 
> - You are not logged in to your account: see File > Options.
> - You may need to log out and log back in to refresh your token.
> - You do not have permission to access this repository.
> - The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
> - If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
> - If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
> - If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.
> 
> Would you like to retry cloning `Fantasy-Calendar`?

Which it doesn't do on any other projects ... I'm suspecting permissions are a factor this time.

**To Reproduce**
1. Open Github Desktop on Windows. 
    a. Be on an account which is not already contributing to the repo.
    b. Assure correct login and SSH keys to assure these aren't an issue (same error is thrown if they are issues).
3. Open the repo on Github via the URL, or clicking on the "Open with Github Desktop" link
    a. NOTE: This is also failing in the bash CLI via SSL.
4. Wait for it to fail, about 80% of the way through.

**Expected behavior**
Completion of the cloning, 

**Desktop:**
 - Multiple browsers (e.g., entirely not a browser issue)
 - Windows 11 (fully updated)
 - GitHub Desktop 3.07 (x64) (latest version as of this post)

**Comment by V13Axel** [comment]
This is from a bug in Github Desktop, caused by the fact that Fantasy Calendar has a private submodule: https://github.com/desktop/desktop/issues/3242

The only solution is to avoid using Github Desktop, and use the command-line or some other method (Such as the `git` VSCode extension).
