### ISSUE TITLE
[BUG] Cannot view calendar; multiple modal prompts

### ISSUE THREAD

**Issue by NullCascade** [fantasycalendar/Fantasy-Calendar#297]
**Link to your calendar**
[Calendar link](https://app.fantasy-calendar.com/calendars/8b00c79a4c8a92808ad2a69ecf1cd184)

**Describe the bug**
When opening either of my calendars (one provided above), I get an overlay of multiple modal windows. These prompt me to edit an era description, or edit events. The modals cannot be closed.

**To Reproduce**
1. Open the calendar.

**Expected behavior**
When opening the calendar, I should be taken to the general view of the calendar.

**Screenshots**
![image](https://user-images.githubusercontent.com/720169/198664132-614c728a-5358-4beb-9b11-9d5dc6ff07f2.png)

**Desktop (please complete the following information):**
 - Firefox 106.0.1 (64-bit)
 - Chrome 107.0.5304.88 (Official, 64-bit)

I have deleted all storage/cookies related to fantasy-calendar.com and signed back in. There was no change to the issue.

**Additional context**
Console context is available for [Chrome](https://user-images.githubusercontent.com/720169/198667635-d963a03e-8006-4858-95ea-28df1fd0ad46.png) and [Firefox](https://user-images.githubusercontent.com/720169/198668491-aa69646c-0f7e-4ad7-aa79-ebef3cafd5a9.png).

**Comment by V13Axel** [comment]
Looks like unpkg.com is and/or was having issues, which resulted in this. Not really a bug, so much as a third-party failure.

That said, I'm going to leave this open, as we'll be looking into bundling the affected libraries into our main app.js to avoid this kind of issue in the future.

**Comment by NullCascade** [comment]
Issue confirmed resolved on unpkg's end by issuer.

I appreciate the fast diagnosis and support both here and with others on Discord.
