### ISSUE TITLE
"Create seasonal events" button creates events for every season

### ISSUE THREAD

**Issue by V13Axel** [fantasycalendar/Fantasy-Calendar#31]
Currently we're just looping through all seasons and creating seasonal events for all of them.

https://github.com/fantasycalendar/Fantasy-Calendar/blob/ab8ab5ae91a33c04e36d7c22cc7d4ec4f63f7f97/resources/js/calendar/calendar_inputs_edit.js#L446-L460

Equinoxes and solstices are based on longest/shortest days of the year, so a world with 50 seasons would still only have two of either.

Would be neato, methinks, to actually calculate those days and somehow create the events based on that.

**Comment by Haxxer** [comment]
Fixed with 7c0551a
