### ISSUE TITLE
[BUG] Season_Based_Time is undefined

### ISSUE THREAD

**Issue by JellybeanBoom** [fantasycalendar/Fantasy-Calendar#316]
I'll be honest, I don't really know what I did. I switched my seasons over to the length based setting and since then my calender's been bugged. Now I can't even see it. My months and weeks are still there, but my events events list is blank, although the description on the calender select page does still have them as there.

**Comment by JellybeanBoom** [comment]
Oh right, sorry! Here: https://app.fantasy-calendar.com/calendars/b5cf83efd082dd3c070393d0c00ddac1/edit

**Comment by Haxxer** [comment]
Not sure what caused it, but I created a new location, and then switched to your old location, and now the calendar works :) Closing as fixed

**Comment by JellybeanBoom** [comment]
Oh, great! Thank you so much, you made a really cool tool :)
