### ISSUE TITLE
Docker build fails in multiple places.

### ISSUE THREAD

**Issue by Faeranne** [fantasycalendar/Fantasy-Calendar#324]
(note, I removed the template since the bug template seems specific to bugs in the application, while this is a self-hosting bug)

When attempting to build the main docker image, multiple build steps have issues.

First, during one of the composer steps, as it is looking for items in `node_modules` after that folder has already been deleted.  I've moved the rm command to the end of the Dockerfile to alleviate this for now.

Second, weather-icons is being installed using the `ssh://` protocol, which fails if you do not have commit access.  I replaces the entry with a `https://` version to alleviate this.

Third, `npm run production` seems to be looking for files in a `/vendor` folder.  I currently have no idea how to get around this, as I'm not even sure what it was supposed to be.

This seems to be a long standing issue that has completely disabled the use of docker, and thus the current recommended self-hosting build.  I'm not sure what needs to be changed to get this back up in working order, but I'm currently doing what I can to match up the current github actions and bring this back into working order on my own.  Any notes here would be very appreciated, as the current docker-hub build is years out of date.

**Comment by Faeranne** [comment]
So after looking over things, I get the impression the docker file hasn't been updated for the 2.0 version.  Is it still somewhat valid for the 2.0, or should I start with the development versions of the docker files?

**Comment by V13Axel** [comment]
Yeah, the unified Dockerfile is pretty old - We had a unified Docker image that was actually being used to serve up the production site.

The _easiest_ way right now would be to run the development docker-compose file, but I'm gonna give it a look and see about updating the unified image this evening.

**Comment by V13Axel** [comment]
@Faeranne I've just pushed an update to `master` that fixes the Dockerfile build and brings it up to date with the last few releases. Important note: You'll want to create your .env file and put your `FONTAWESOME_NPM_AUTH_TOKEN` into it. (See https://fontawesome.com/docs/web/setup/packages)

**Comment by Faeranne** [comment]
Awesome!  I'm building it now.  And yeah, I saw the Mix stage takes quite a while, but that's understandable.  Since it's only on the build, it's all good.  Thanks for the update!
