### ISSUE TITLE
Error on line 3745 & 3746

### ISSUE THREAD

**Issue by SANSd20** [fantasycalendar/Fantasy-Calendar#33]
Posted to Discord

Getting this error when loading the calendars. According to Wasp, its just grabbing the name of the child calendar connected to that calendar. I only have one calendar, and do not believe I had ever linked this calendar to another.

Now I am getting the same error message, but coming from line 3476 with different ID number

Username is Sans

![3745](https://user-images.githubusercontent.com/23466008/67696709-57245700-f975-11e9-8ead-a81abc3e5c91.png)
![3746](https://user-images.githubusercontent.com/23466008/67696710-57245700-f975-11e9-8624-d304fffc69a4.png)

**Comment by Haxxer** [comment]
I fixed your calendar on the server side - it seems that the calendar somehow set its `children` column to `[undefined]` and its `master_hash` to `NULL` which obviously is not normal behavior. Do you remember if you touched any of the link controls in the calendar before saving? Even just opening and then closing them?

**Comment by Haxxer** [comment]
@V13Axel Please take a quick look on the backend if anything could have caused this :)

**Comment by SANSd20** [comment]
> I fixed your calendar on the server side - it seems that the calendar somehow set its `children` column to `[undefined]` and its `master_hash` to `NULL` which obviously is not normal behavior. Do you remember if you touched any of the link controls in the calendar before saving? Even just opening and then closing them?

Yeah, I did.

**Comment by V13Axel** [comment]
So I spent some time reviewing this and nothing jumps out to me as a smoking gun. It's very strange.

I'm going to close this for now, since we've got linking improvements in the works - But if it comes back up we'll revisit.
