### ISSUE TITLE
Create Seasonal Events Lock-up

### ISSUE THREAD

**Issue by zerowacked** [fantasycalendar/Fantasy-Calendar#46]
Chrome Version 78.0.3904.70 (Official Build) (64-bit)

![Error screen + Console](https://user-images.githubusercontent.com/22608468/68079435-5fd2be00-fdb7-11e9-8dec-4d5ed5d8ecac.JPG)

Steps to reproduce:
1.) 192 day calendar
2.) 3 seasons (set to 64 day duration, 0 peak duration)
3.) Select **Create Seasonal Events**

Error in top right displays..

> Cannot read property 'data' of undefined
>     at Object.evaluate_calendar_data (worker_calendar.js?v=1572736700340:765)
>     at onmessage (worker_calendar.js?v=1572736700340:1419)

Link to calendar: http://beta.fantasy-calendar.com/calendars/b167395322ed706415b3bf8ab77b60ee

**Comment by Haxxer** [comment]
I just tried this on your calendar and whatever caused this problem for you seems to have been resolved lately
