### ISSUE TITLE
Single-day events doubling when used as target

### ISSUE THREAD

**Issue by RedaunAmarien** [fantasycalendar/Fantasy-Calendar#48]
When using an event set to a specific day as a target for another event, the first event is shown twice in the calendar.

In the example below, Chapters 2 and 4A are both set to occur "one day after" Chapters 1 and 3, respectively. Chapters 1 and 3 are set to the specific dates shown.

Originally, I had Chapter 1 set to "15 days before Ariston's Birthday" and that made Ariston's Birthday display as doubled.

If there is a chain of targeted events, only the root of the chain (the one with the set date) is shown as doubled.

![DoubledEvents](https://user-images.githubusercontent.com/50568822/68080667-b5ae6280-fdc5-11e9-9937-623be3909882.png)

**Comment by V13Axel** [comment]
Good find. Sans had pointed out the doubling to me but I hadn't seen the cause. We'll found!
