### ISSUE TITLE
Cannot delete events

### ISSUE THREAD

**Issue by DarthRednax** [fantasycalendar/Fantasy-Calendar#64]
![image](https://user-images.githubusercontent.com/6236359/70400460-1cdcb980-19f9-11ea-8c44-107e40073d99.png)

**Comment by V13Axel** [comment]
Can you provide a link to your calendar?

**Comment by V13Axel** [comment]
The bug that caused this has already been fixed, but this was the result of a leftover bad formatting issue. fixed now.
