### ISSUE TITLE
Leap days/years not quite working on "view" mode

### ISSUE THREAD

**Issue by V13Axel** [fantasycalendar/Fantasy-Calendar#65]
See below. Left is edit, right is view:

![image](https://user-images.githubusercontent.com/2779682/70490892-a958ac00-1acd-11ea-9324-2131d1eefcf8.png)

This is on https://beta.fantasy-calendar.com/calendars/da379852499bce611608e5cbd8b089ce

**Comment by Haxxer** [comment]
This issue cannot be reproduced without having year zero enabled

**Comment by Haxxer** [comment]
Year zero was removed, no longer an issue.
