### ISSUE TITLE
Event logic identifies wrong day as day 1

### ISSUE THREAD

**Issue by sashemi** [fantasycalendar/Fantasy-Calendar#95]
On the first season in the list, "day 1" in event conditions identifies first and second day of the season:
![season 1](https://user-images.githubusercontent.com/59229887/81241241-9f749f80-8fbe-11ea-9976-c30dd07f2649.png)

On second and subsequent seasons "day 1" in event conditions does not identify a day. "day 2" will identify first day of the season, and so on.. in the picture below, "day 2" is configured in the event.
![season 2](https://user-images.githubusercontent.com/59229887/81241327-c7640300-8fbe-11ea-84ae-5b298279afa7.png)

Calendar for testing: https://beta.fantasy-calendar.com/calendars/325349d50d9915104d1f0f669c5e11db/edit

**Comment by Haxxer** [comment]
Latest build has fixed this (hopefully)
